spring.application.name=AuthMicroservice

# ?????? ??????
spring.mail.host=smtp.gmail.com
spring.mail.username= evgenijslavkin3@gmail.com
spring.mail.password= qdopkhacvlzpfbcf
spring.mail.port = 587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




# ?????? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


# ?????? jwt 30 ??? ? 7 ????

spring.jwt.secretkey = as;dlma;dmsdsd'q;m ew;1mw31m31nm3n1n31n31bn3k12b3k1babwasdasdasd
spring.jwt.expiration = 1800000
spring.jwt.refreshtokenexpiration = 604800000